### ISSUE TITLE
test error

### ISSUE THREAD

**Issue by zdyshine** [IanYeung/MGLD-VSR#4]
test cmd:
python scripts/vsr_val_ddpm_text_T_vqganfin_oldcanvas_tile.py   --config configs/mgldvsr/mgldvsr_512_realbasicvsr_deg.yaml   --ckpt experiment/MGLD-VSR-Pretrained-Models/mgldvsr_unet.ckpt   --vqgan_ckpt experiment/MGLD-VSR-Pretrained-Models/video_vae_cfw.ckpt   --seqs-path /test/SR/png/val/   --outdir results   --ddpm_steps 50   --dec_w 1.0   --colorfix_type adain   --select_idx 0   --n_gpus 1

----------------------- Error1
Traceback (most recent call last):
  File "scripts/vsr_val_ddpm_text_T_vqganfin_oldcanvas_tile.py", line 29, in <module>
    from scripts.util_flow import forward_backward_consistency_check
ModuleNotFoundError: No module named 'scripts.util_flow'

----------------------- Error2
New error message appears after modifying the code
Traceback (most recent call last):
  File "scripts/vsr_val_ddpm_text_T_vqganfin_oldcanvas_tile.py", line 29, in <module>
    from util_flow import forward_backward_consistency_check
  File "/test/MGLD-VSR/scripts/util_flow.py", line 17, in <module>
    from basicsr.archs.raft_arch import RAFT_SR
ModuleNotFoundError: No module named 'basicsr.archs.raft_arch'

----------------------- Error3
New error message appears after modifying the code
>>>>>>>>>>color correction>>>>>>>>>>>
Use adain color correction
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
Loading model from experiment/MGLD-VSR-Pretrained-Models/mgldvsr_unet.ckpt
Global Step: 42000
Traceback (most recent call last):
  File "scripts/vsr_val_ddpm_text_T_vqganfin_oldcanvas_tile.py", line 555, in <module>
    main()
  File "scripts/vsr_val_ddpm_text_T_vqganfin_oldcanvas_tile.py", line 297, in main
    model = load_model_from_config(config, f"{opt.ckpt}")
  File "scripts/vsr_val_ddpm_text_T_vqganfin_oldcanvas_tile.py", line 97, in load_model_from_config
    model = instantiate_from_config(config.model)
  File "/test/AwesomeAI/StableSR/ldm/util.py", line 85, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "/test/AwesomeAI/StableSR/ldm/util.py", line 101, in get_obj_from_str
    return getattr(importlib.import_module(module, package=None), cls)
  File "/opt/conda/envs/stablesr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/test/AwesomeAI/StableSR/ldm/models/diffusion/ddpm.py", line 24, in <module>
    from ldm.models.autoencoder import VQModelInterface, IdentityFirstStage, AutoencoderKL
  File "/test/AwesomeAI/MGLD-VSR/ldm/models/autoencoder.py", line 14, in <module>
    from ldm.modules.diffusionmodules.util import from_5d_to_4d, from_4d_to_5d
ImportError: cannot import name 'from_5d_to_4d' from 'ldm.modules.diffusionmodules.util' (/test/AwesomeAI/StableSR/ldm/modules/diffusionmodules/util.py)

I guess the environment was not set up properly, but I don't know how to modify it. Do you have any suggestions

**Comment by IanYeung** [comment]
> test cmd: python scripts/vsr_val_ddpm_text_T_vqganfin_oldcanvas_tile.py --config configs/mgldvsr/mgldvsr_512_realbasicvsr_deg.yaml --ckpt experiment/MGLD-VSR-Pretrained-Models/mgldvsr_unet.ckpt --vqgan_ckpt experiment/MGLD-VSR-Pretrained-Models/video_vae_cfw.ckpt --seqs-path /test/SR/png/val/ --outdir results --ddpm_steps 50 --dec_w 1.0 --colorfix_type adain --select_idx 0 --n_gpus 1
> 
> ----------------------- Error1 Traceback (most recent call last): File "scripts/vsr_val_ddpm_text_T_vqganfin_oldcanvas_tile.py", line 20, in from ldm.models.diffusion.ddim import DDIMSampler ModuleNotFoundError: No module named 'ldm.models'
> 
> ----------------------- Error2 New error message appears after modifying the code Traceback (most recent call last): File "scripts/vsr_val_ddpm_text_T_vqganfin_oldcanvas_tile.py", line 28, in from basicsr.archs.arch_util import resize_flow ModuleNotFoundError: No module named 'basicsr'
> 
> I guess the environment was not set up properly, but I don't know how to modify it. Do you have any suggestions

I guess you can probably try
```
export PYTHONPATH=".:$PYTHONPATH"
```

**Comment by zdyshine** [comment]
> > test cmd: python scripts/vsr_val_ddpm_text_T_vqganfin_oldcanvas_tile.py --config configs/mgldvsr/mgldvsr_512_realbasicvsr_deg.yaml --ckpt experiment/MGLD-VSR-Pretrained-Models/mgldvsr_unet.ckpt --vqgan_ckpt experiment/MGLD-VSR-Pretrained-Models/video_vae_cfw.ckpt --seqs-path /test/SR/png/val/ --outdir results --ddpm_steps 50 --dec_w 1.0 --colorfix_type adain --select_idx 0 --n_gpus 1
> > ----------------------- Error1 Traceback (most recent call last): File "scripts/vsr_val_ddpm_text_T_vqganfin_oldcanvas_tile.py", line 20, in from ldm.models.diffusion.ddim import DDIMSampler ModuleNotFoundError: No module named 'ldm.models'
> > ----------------------- Error2 New error message appears after modifying the code Traceback (most recent call last): File "scripts/vsr_val_ddpm_text_T_vqganfin_oldcanvas_tile.py", line 28, in from basicsr.archs.arch_util import resize_flow ModuleNotFoundError: No module named 'basicsr'
> > I guess the environment was not set up properly, but I don't know how to modify it. Do you have any suggestions
> 
> I guess you can probably try
> 
> ```
> export PYTHONPATH=".:$PYTHONPATH"
> ```

resolved

**Comment by zdyshine** [comment]
Is it correct to load the model with many Missing Keys:

Global seed set to 42
>>>>>>>>>>color correction>>>>>>>>>>>
Use adain color correction
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
Loading model from experiment/MGLD-VSR-Pretrained-Models/mgldvsr_unet.ckpt
Global Step: 42000
LatentDiffusionVSRTextWT: Running in eps-prediction mode
Setting up MemoryEfficientSelfAttention. Query dim is 1280, using 20 heads.
DiffusionWrapper has 935.32 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 64, 64) = 16384 dimensions.
making attention of type 'vanilla' with 512 in_channels
Encoder Restored from experiment/checkpoints/v2-1_512-ema-pruned.ckpt with 0 missing and 1242 unexpected keys
<<<<<<<<<<<<>>>>>>>>>>>>>>>
Restored from experiment/checkpoints/v2-1_512-ema-pruned.ckpt with 588 missing and 38 unexpected keys
Missing Keys: ['model.diffusion_model.input_blocks.1.0.spade.param_free_norm.weight', ...]

Unexpected Keys: ['model_ema.decay', 'model_ema.num_updates', 'model.diffusion_model.middle_block.1.norm.weight', 'model.diffusion_model.middle_block.1.norm.bias', 'model.diffusion_model.middle_block.1.proj_in.weight', 'model.diffusion_model.middle_block.1.proj_in.bias', ]

>>>>>>>>>>>>>>>>model>>>>>>>>>>>>>>>>>>>>
['diffusion_model.input_blocks.1.0.spade.param_free_norm.weight', ...]

>>>>>>>>>>>>>>>>>cond_stage_model>>>>>>>>>>>>>>>>>>>
[]
>>>>>>>>>>>>>>>>structcond_stage_model>>>>>>>>>>>>>>>>>>>>
['time_embed.0.weight', 'time_embed.0.bias', 'time_embed.2.weight', ...]

Loading model from experiment/MGLD-VSR-Pretrained-Models/video_vae_cfw.ckpt
Global Step: 42000
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 64, 64) = 16384 dimensions.
making attention of type 'vanilla' with 512 in_channels

loaded pretrained LPIPS loss from taming/modules/autoencoder/lpips/vgg.pth
Encoder Restored from experiment/checkpoints/v2-1_512-ema-pruned.ckpt with 230 missing and 994 unexpected keys
Missing Keys: ['decoder.temporal_mixing.temporal_alpha',  ...]

Unexpected Keys: ['betas', 'alphas_cumprod', 'alphas_cumprod_prev', ...]

>>>>>>>>>>>>>>>>>missing>>>>>>>>>>>>>>>>>>>
['decoder.temporal_mixing.temporal_alpha', ...]

>>>>>>>>>>>>>>>>>trainable_list>>>>>>>>>>>>>>>>>>>
['decoder.temporal_mixing.temporal_alpha',...]

>>>>>>>>>>>>>>>>>Untrainable_list>>>>>>>>>>>>>>>>>>>
['encoder.conv_in.weight', 'encoder.conv_in.bias', ...]

cmd:
CUDA_VISIBLE_DEVICES=2 python scripts/vsr_val_ddpm_text_T_vqganfin_oldcanvas_tile.py   --config configs/mgldvsr/mgldvsr_512_realbasicvsr_deg.yaml   --ckpt experiment/MGLD-VSR-Pretrained-Models/mgldvsr_unet.ckpt   --vqgan_ckpt experiment/MGLD-VSR-Pretrained-Models/video_vae_cfw.ckpt   --seqs-path /test/SR/png/val/   --outdir results   --ddpm_steps 50   --dec_w 1.0   --colorfix_type adain   --select_idx 0   --n_gpus 1

**Comment by IanYeung** [comment]
Yes, it is correct.

**Comment by hhuyujie** [comment]
hello, do you have such problem:
![image](https://github.com/IanYeung/MGLD-VSR/assets/47933624/4afb6dfc-f512-4990-b349-7bd512426410)
Thank you and I hope to receive your reply as soon as possible~
